version: '3.8'

services:
  whisper-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MODEL_PATH=base
      - MAX_CONTENT_LENGTH=16777216  # 16MB
    volumes:
      - ./tmp:/tmp  # 挂载 /tmp 目录用于临时文件存储
      - ./whisper-cache:/root/.cache  # 挂载缓存
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0', '1'] # Select a gpu, or
              count: all
              capabilities: [gpu]
